### ISSUE TITLE
[MPMD-2] pmd has problems with package-info.java.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-pmd-plugin#229]
**[Bernd Bohmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bommel)** opened **[MPMD-2](https://issues.apache.org/jira/browse/MPMD-2?redirect=false)** and commented

pmd has problems with package-info.java. Please exclude package-info.java from report.

package-info.java can be used in place of package.html (which supports only comments, not annotations)

Please update to pmd version 3.3

Embedded error: Failure executing PMD for:

myfaces/tobago/taglib/component/package-info.java
Encountered "package" at line 27, column 1.
Was expecting one of:
"class" ...
"final" ...
"interface" ...
\<IDENTIFIER> ...
"@" ...
"public" ...
"static" ...
"protected" ...
"private" ...
"abstract" ...
"synchronized" ...
"native" ...
"transient" ...
"volatile" ...
"strictfp" ...

---

**Attachments:**
- [PmdReport.java.patch](https://issues.apache.org/jira/secure/attachment/12717252/PmdReport.java.patch) (_755 bytes_)

**Comment by jira-importer** [comment]
**[Bernd Bohmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bommel)** commented

patch included

**Comment by jira-importer** [comment]
**[Darren Hartford](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dhartford)** commented

verify issue with package-info.java.  Critical for EJB3-type projects.

Sample package-info.java:

---

`@javax`.persistence.NamedQueries(
{
`@javax`.persistence.NamedQuery(
name="findAllTable",
queryString="SELECT tbl FROM Table tbl"
),
`@javax`.persistence.NamedQuery(
name="findAllTable2",
queryString="SELECT tbl FROM Table2 tbl"
)

}
)
package my.package.ejb3;

---

verified against 2.0-alpha-2 release.

**Comment by jira-importer** [comment]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** commented

The PMD plugin has been updated to use PMD 3.4.  Is this issue still relevant?

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

should be fixed. Please reopen if reproducible.

**Comment by jira-importer** [comment]
**[Bernd Bohmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bommel)** commented

I get the same error with the new version.

[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-pmd-plugin:2.0-beta-1:pmd' -->
...
Caused by: org.apache.maven.reporting.MavenReportException: Failure executing PMD for: /home/bommel/work/incubator-tobago/tobago-core/src/main/java/org/apache/myfaces/tobago/taglib/component/package-info.java
at org.apache.maven.plugin.pmd.PmdReport.executeReport(PmdReport.java:269)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:98)
at org.apache.maven.plugins.site.SiteMojo.generateReportsPages(SiteMojo.java:802)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:301)
... 18 more
Caused by: net.sourceforge.pmd.ast.ParseException: Encountered "package" at line 27, column 1.
Was expecting one of:
"class" ...
"final" ...
"interface" ...
\<IDENTIFIER> ...
"@" ...
"public" ...
"static" ...
"protected" ...
:
Please exclude package-info.java from report.
A pmd report on package-info.java isn't useful.

**Comment by jira-importer** [comment]
**[Bernd Bohmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bommel)** commented

With the patch it's works.

**Comment by jira-importer** [comment]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** commented

Patched.  Thanks Bernd.
