### ISSUE TITLE
[MPMD-1] PMD does not work on dutch locale

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-pmd-plugin#230]
**[Wim Deblauwe](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wim.deblauwe@gmail.com)** opened **[MPMD-1](https://issues.apache.org/jira/browse/MPMD-1?redirect=false)** and commented

I get the following error when running mvn site with pmd report enabled:

[ERROR] FATAL ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Can't find bundle for base name pmd-report, locale nl_NL
[INFO] ----------------------------------------------------------------------------
[INFO] Trace
java.util.MissingResourceException: Can't find bundle for base name pmd-report, locale nl_NL
at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:837)
at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:806)
at java.util.ResourceBundle.getBundle(ResourceBundle.java:700)
at org.apache.maven.plugin.pmd.PmdReport.getBundle(PmdReport.java:232)
at org.apache.maven.plugin.pmd.PmdReport.getName(PmdReport.java:82)
at org.apache.maven.plugins.site.ReportComparator.compare(ReportComparator.java:40)
at java.util.Arrays.mergeSort(Arrays.java:1284)
at java.util.Arrays.sort(Arrays.java:1223)
at java.util.Collections.sort(Collections.java:159)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:240)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:399)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:469)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:448)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:301)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:268)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:137)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:316)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:113)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 10 seconds
[INFO] Finished at: Tue Nov 15 14:42:35 CET 2005
[INFO] Final Memory: 9M/16M
[INFO] ----------------------------------------------------------------------------

regards,

Wim

---
No further details from [MPMD-1](https://issues.apache.org/jira/browse/MPMD-1?redirect=false)

**Comment by jira-importer** [comment]
**[Jose Gonzalez Gomez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jgonzalez.openinput@gmail.com)** commented

Same for es_ES

**Comment by jira-importer** [comment]
**[domi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arachus)** commented

I have the same and also found out there are more plugins having the same problem e.g. checkstyle (http://jira.codehaus.org/browse/MCHECKSTYLE-15?rc=1)

**Comment by jira-importer** [comment]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** commented

I don't understand why you are seeing this exception.  The PMD plugin only supports the default locale (English) and French.  According to the ResourceBundle javadoc, it should fall back to the default if the given locale (like NL) is not supported.  In other words, I would expect the behavior for you to see an English report rather than an exception.  I don't have a lot of i18n experience - anyone else have a better idea of what's going on?

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

This has been solved in SVN already.
See http://svn.apache.org/viewcvs.cgi?rev=326881&view=rev
