### ISSUE TITLE
[MPMD-381] MPMD-323-ruleset-basedir-jgitver is broken or flaky on JDK 17 windows

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-pmd-plugin#349]
**[Elliotte Rusty Harold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elharo)** opened **[MPMD-381](https://issues.apache.org/jira/browse/MPMD-381?redirect=false)** and commented

```
Error:  'other' has different root
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Running post-build script: D:\a\maven-pmd-plugin\maven-pmd-plugin\target\it\MPMD-323-ruleset-basedir-jgitver\verify.groovy
Assertion failed: 

assert pmdXml.exists()
       |      |
       |      false
       D:\a\maven-pmd-plugin\maven-pmd-plugin\target\it\MPMD-323-ruleset-basedir-jgitver\target\pmd.xml

	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:436)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:670)
	at Script1.run(Script1.groovy:21)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:427)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:461)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:436)
	at org.apache.maven.shared.scriptinterpreter.GroovyScriptInterpreter.evaluateScript(GroovyScriptInterpreter.java:76)
	at org.apache.maven.shared.scriptinterpreter.ScriptRunner.executeRun(ScriptRunner.java:236)
	at org.apache.maven.shared.scriptinterpreter.ScriptRunner.run(ScriptRunner.java:161)
	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.runPostBuildHook(AbstractInvokerMojo.java:2154)
	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.runBuild(AbstractInvokerMojo.java:2129)
	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.runBuild(AbstractInvokerMojo.java:1721)
	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.lambda$runBuilds$4(AbstractInvokerMojo.java:1431)
	at org.apache.maven.plugins.invoker.JobExecutor.lambda$null$1(JobExecutor.java:69)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
*** end build.log for: MPMD-323-ruleset-basedir-jgitver\pom.xml ***

Error:  -------------------------------------------------
Error:  
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 44, Failed: 1, Errors: 0, Skipped: 4
[INFO] -------------------------------------------------
```

---
No further details from [MPMD-381](https://issues.apache.org/jira/browse/MPMD-381?redirect=false)

**Comment by jira-importer** [comment]
**[Elliotte Rusty Harold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elharo)** commented

see https://github.com/apache/maven-pmd-plugin/pull/133 which is a trivial docs change that should have no effect on any integration  test. Same error on other PRs.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

That is likely related to the drive letter being uppercase and lowercase.
