### ISSUE TITLE
[MPMD-22] PMD plugin <configuration> should accept dependency entries

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-pmd-plugin#398]
**[Subhash Chandran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=subwiz)** opened **[MPMD-22](https://issues.apache.org/jira/browse/MPMD-22?redirect=false)** and commented

As described here:

http://maven.apache.org/plugins/maven-pmd-plugin/howto.html

The PMD plugin supports configuration of custom ruleset XML files. But in our organization, we have written custom ruleset XMLs that refer Java classes (our PMD extension dependencies). The configuration of the PMD plugin should allow these dependencies to be specified.

Since we do not have this feature in the current release, we at our organization are forced to maintain a fork of the PMD plugin with the necessary dependencies added.

A suggested format:

\<configuration>
\<rulesets>
\<ruleset>/rulesets/basic.xml\</ruleset>
\<ruleset>/rulesets/controversial.xml\</ruleset>
\<ruleset>d:\rulesets\strings.xml\</ruleset>
\<ruleset>http://localhost/design.xml\</ruleset>
\</rulesets>
\<dependency>
\<groupId>junit\</groupId>
\<artifactId>junit\</artifactId>
\<version>4.0\</version>
\<scope>test\</scope>
\</dependency>

    <format>xml</format>
    <linkXref>true</linkXref>
    <sourceEncoding>utf-8</sourceEncoding>
    <minimumTokens>100</minimumTokens>

\</configuration>

---

**Issue Links:**
- [MNG-2173](https://issues.apache.org/jira/browse/MNG-2173) support \<dependencies> in \<reporting> plugins
 (_**"depends upon"**_)
- [MSITE-444](https://issues.apache.org/jira/browse/MSITE-444) reporting section should allow additional dependencies in plugins as well
 (_**"depends upon"**_)

4 votes, 8 watchers

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Have you tried setting \<dependencies> inside \<plugin>
That's how it should work

**Comment by jira-importer** [comment]
**[Subhash Chandran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=subwiz)** commented

We tried that. We are getting this exception trace:

----------------------------start trace------------------------------

Reason: Parse error reading POM. Reason: Unrecognised tag: 'dependencies' (position: START_TAG seen ...\</configuration>\n\n\t\t\<dependencies>... `@94`:17)

[INFO] ----------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.reactor.MavenExecutionException: Parse error reading POM. Reason: Unrecognised tag: 'dependencies' (position: START_TAG seen ...\</configuration>\n\n\t\t\<dependencies>... `@94`:17)
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:365)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:278)

----------------------------end trace------------------------------

Note that we are trying this in M2.0.2 release. Is this \<dependencies> support inside \<plugin> part of the yet to be released M2.0.3?

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

It worked since 2.0

http://maven.apache.org/ref/2.0.3-SNAPSHOT/maven-model/maven.html

\<build>
\<plugins>
\<plugin>
\<groupId/>
\<artifactId/>
\<version/>
\<dependencies>
\<dependency>
\<groupId/>
\<artifactId/>
\<version/>
\</dependency>
\</dependencies>
\</plugin>
\</plugins>
\</build>

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

It's a known issue that \<reporting> doesn't. The bug is in core, and checkstyle has a similar issue.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

one workaround to try is putting the dependency on the site plugin in the build section.

**Comment by jira-importer** [comment]
**[Subhash Chandran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=subwiz)** commented

I have located the core issue:

http://jira.codehaus.org/browse/MNG-2173

Can this issue be linked to that one, or should this one be closed?

**Comment by jira-importer** [comment]
**[Arnaud Heritier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aheritier)** commented

It's working (for now) to add it as an extension because it adds it in a classloader available for maven's core and plugins but it's not something that we would like to recommand.
Extensions mechanism is used to add new functionnalities in maven and not to share data between plugins.
We prefer that you add this dependency in the plugin dependency :

```xml
<build>
 <plugins>
  <plugin>
   <artifactId>maven-pmd-plugin</artifactId>
   <dependencies>
    <dependency>
     <groupId>cz.aspectworks</groupId>
     <artifactId>cz.aspectworks.build</artifactId>
     <version>0.2.0</version>
    </dependency>
   </dependencies>
  </plugin>
 </plugins>
</build>
```
