### ISSUE TITLE
[MPMD-58] sourceEncoding honoured with pmd but not cpd

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-pmd-plugin#426]
**[M. Rohrmoser](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mro)** opened **[MPMD-58](https://issues.apache.org/jira/browse/MPMD-58?redirect=false)** and commented

If the source (*.java) contains non-Ascii Characters, e.g. in field names, pmd:check works fine but pmd:cpd-check fails with the stacktrace

[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: An error has occurred in CPD Report report generation.
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:559)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkProjectLifecycle(DefaultLifecycleExecutor.java:898)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkLifecycle(DefaultLifecycleExecutor.java:734)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:505)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:488)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:458)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred in CPD Report report generation.
at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:79)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
... 19 more
Caused by: net.sourceforge.pmd.ast.TokenMgrError: Lexical error at line 32, column 33.  Encountered: "\ufffd" (65533), after : ""
at net.sourceforge.pmd.ast.JavaParserTokenManager.getNextToken(JavaParserTokenManager.java:2037)
at net.sourceforge.pmd.cpd.JavaTokenizer.tokenize(JavaTokenizer.java:69)
at net.sourceforge.pmd.cpd.CPD.add(CPD.java:97)
at net.sourceforge.pmd.cpd.CPD.add(CPD.java:50)
at org.apache.maven.plugin.pmd.CpdReport.executeReport(CpdReport.java:102)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:98)
at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:73)
... 21 more

The pom is:
\<project>
...
\<reporting>
\<plugins>
\<plugin>
\<groupId>org.apache.maven.plugins\</groupId>
\<artifactId>maven-pmd-plugin\</artifactId>
\<configuration>
\<verbose>true\</verbose>
\<linkXref>true\</linkXref>
\<sourceEncoding>utf-8\</sourceEncoding>
\<minimumTokens>100\</minimumTokens>
\<targetJdk>1.5\</targetJdk>
\<excludes>
\</excludes>
\</configuration>
\</plugin>
\</plugins>
\</reporting>
...
\</project>

---

**Affects:** 2.2

**Attachments:**
- [MPMD-58_sourceEncoding.txt](https://issues.apache.org/jira/secure/attachment/12717280/MPMD-58_sourceEncoding.txt) (_2.01 kB_)
- [MPMD-58.zip](https://issues.apache.org/jira/secure/attachment/12717302/MPMD-58.zip) (_1.81 kB_)

1 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Lasse Koskela](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lkoskela)** commented

I could not reproduce this error. Could you perhaps attach a zip file containing your entire project, including at least one source file that has such non-ascii characters?

**Comment by jira-importer** [comment]
**[Jörg Hohwiller](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=joerg.hohwiller@sdm.de)** commented

See MPMD-7
The error can be reproduced very easy. Just write an UTF-8 *.java source file and add some non-ascii chars into Javadoc or whereever.
Then run maven (ensure file.encoding is NOT UTF-8) and CPD will fail even if encoding is set to UTF-8.

See also MNG-2932

**Comment by jira-importer** [comment]
**[Xavier Le Vourch](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xlv)** commented

The attached patch sets the encoding for CPD in a similar way to what's done for the pmd goal in PmdReport.java.

The error message for an invalid encoding looks the same but the processing is different as CPD transforms encoding exceptions into RuntimeException so the encoding is tested before calling the cpd methods.

Xavier

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Thanks for the patch Xavier.

Do you know if this is a problem only on Linux?

I have tried to reproduce this on my Windows box and I get a different error than reported in this issue. However the errors I get when I run pmd:check is the similar to what I get when I run pmd:cpd-check. See attached test-case.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Since I cannot test this I need some help verifying that the patch works. I've applied the patch and deployed a new 2.3-SNAPSHOT. Please test it and report back if it works.

**Comment by jira-importer** [comment]
**[Xavier Le Vourch](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xlv)** commented

It works for me on Linux but I'm the one who submitted the patch so that's expected and I figured you needed some external confirmation... but maybe not...

Xavier
