### ISSUE TITLE
[MPMD-60] @SuppressWarnings causes maven PMD plugin to fail on building report

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-pmd-plugin#429]
**[Pieter Iserbyt](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sandb)** opened **[MPMD-60](https://issues.apache.org/jira/browse/MPMD-60?redirect=false)** and commented

When running mvn pmd:pmd, the plugin crashes at the time it tries to create the report.

This seems to happen when violations are present that are suppressed by a `@SuppressWarnings`("PMD") or `@SuppressWarnings`("PMD.a_warning_name") annotation.

Also, java keywords are not recognized by PMD, e.g. for `@SuppressWarnings`("unused"), violations are logged anyway.

D:\trunk\quality>mvn pmd:check -e
+ Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] Searching repository for plugin with prefix: 'pmd'.
  [INFO] org.apache.maven.plugins: checking for updates from doc-artifactory
  [INFO] org.codehaus.mojo: checking for updates from doc-artifactory
  [WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = 'cc696ab05c9684342aa52c61bdcb7471a264b533'; remote = 'fd019ddf5b11fc51ce35ac7cf10c2ef5b387b0cf' - RETRYING
  [INFO] artifact org.apache.maven.plugins:maven-pmd-plugin: checking for updates from doc-artifactory
  [INFO] ----------------------------------------------------------------------------
  [INFO] Building Diamond Quality
  [INFO]    task-segment: [pmd:check]
  [INFO] ----------------------------------------------------------------------------
  [INFO] Preparing pmd:check
  [INFO] [pmd:pmd]
  [INFO] ------------------------------------------------------------------------
  [ERROR] BUILD ERROR
  [INFO] ------------------------------------------------------------------------
  [INFO] An error has occurred in PMD Report report generation.

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: An error has occurred in PMD Report report generation.
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:564)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkProjectLifecycle(DefaultLifecycleExecutor.java:903)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkLifecycle(DefaultLifecycleExecutor.java:739)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:510)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:493)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:463)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred in PMD Report report generation.
at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:79)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
... 19 more
Caused by: java.lang.NullPointerException
at net.sourceforge.pmd.util.StringUtil.appendXmlEscaped(StringUtil.java:78)
at net.sourceforge.pmd.util.StringUtil.appendXmlEscaped(StringUtil.java:65)
at net.sourceforge.pmd.renderers.XMLRenderer.render(XMLRenderer.java:88)
at org.apache.maven.plugin.pmd.PmdReport.executeReport(PmdReport.java:260)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:98)
at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:73)
... 21 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6 seconds
[INFO] Finished at: Thu Aug 02 11:19:54 CEST 2007
[INFO] Final Memory: 4M/12M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.2

**Comment by jira-importer** [comment]
**[Holger Brands](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hbrands)** commented

We also get this annoying bug.

It seems to be related to issue MPMD-59, so perhaps upgrading to PMD 4.0 will help?

**Comment by jira-importer** [comment]
**[Daniel Kulp](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dkulp)** commented

Fixed due to updating to PMD 4.1 as part of MPMD-59.
