### ISSUE TITLE
[MPMD-142] PMD Report for maven site fails with ClassCastException 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-pmd-plugin#494]
**[Jan Ruzicka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jan.ruzicka)** opened **[MPMD-142](https://issues.apache.org/jira/browse/MPMD-142?redirect=false)** and commented

Maven 2.2.1 is complaining when mvn site is run.
It is stopping in PMD report.
Section from log is below.
This error appeared freshly this morning. The site goal run successfully before.

```
[INFO] Generating "PMD Report" report.
[WARNING] Deprecated API called - not org.apache.maven.doxia.sink.Sink instance and no SinkFactory available. Please update this plugin.
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] java.lang.String cannot be cast to java.io.File
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.ClassCastException: java.lang.String cannot be cast to java.io.File
	at org.apache.maven.plugin.pmd.AbstractPmdReport.getFilesToProcess(AbstractPmdReport.java:284)
	at org.apache.maven.plugin.pmd.PmdReport.generateReport(PmdReport.java:249)
	at org.apache.maven.plugin.pmd.PmdReport.execute(PmdReport.java:175)
	at org.apache.maven.plugin.pmd.PmdReport.executeReport(PmdReport.java:149)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:190)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:144)
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:139)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:269)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:101)
	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:133)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:100)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
	at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

---

**Affects:** 2.7

**Attachments:**
- [testpom.xml](https://issues.apache.org/jira/secure/attachment/12717263/testpom.xml) (_915 bytes_)

**Comment by jira-importer** [comment]
**[Jan Ruzicka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jan.ruzicka)** commented

this error appears for all goals pmd:check, pmd:cpd-check, pmd:pmd, pmd:cpd

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Can you supply a small sample project that exhibits this problem?

**Comment by jira-importer** [comment]
**[Jan Ruzicka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jan.ruzicka)** commented

It seems to be triggered by exclusion using excludeRoots.

**Comment by jira-importer** [comment]
**[Jan Ruzicka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jan.ruzicka)** commented

Empty project with attached pom would trigger the execption.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Jan, thanks for the sample project.

I've reproduced the problem locally and have a fix in the works. In the mean time you can use version 2.6 of the plugin as a work-around.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Please try the 2.7.1-SNAPSHOT that I just deployed.

**Comment by jira-importer** [comment]
**[Jan Ruzicka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jan.ruzicka)** commented

Thank you, the 2.7.1-SNAPSHOT worked without Exception. The biggest delay was fighting Nexus.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Fixed in [r1241358](http://svn.apache.org/viewvc?view=revision&revision=1241358).

**Comment by jira-importer** [comment]
**[Jordan Hein](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jordanh@zootweb.com)** commented

Thanks for the quick fix. For the record my CI builds broke yesterday with this error and I can report that it occurs in version 2.5, 2.6, and 2.7. I did not try any other versions.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Jordan,

This issue only affects 2.7, not any other versions.

**Comment by jira-importer** [comment]
**[Jordan Hein](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jordanh@zootweb.com)** commented

You are right, this effects only 2.7. I only had the pmd plugin configured in the reporting section of my pom and not in the build section, thus I was unwittingly using 2.7. Once I sorted this out for good measure I did test with 2.5 and 2.6 and they both work fine. Thanks again for the quick fix and I'll look forward to the next release.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Added IT to prevent regression (although this is not a Maven 3 issue) [rev. 1241574](http://svn.apache.org/viewvc?rev=1241574&view=rev)

**Comment by jira-importer** [comment]
**[Jan Ruzicka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jan.ruzicka)** commented

is 2.7.1 released? I have troubles finding the release. The Maven Central http://repo1.maven.org/maven2/ doesn't have it nor does the Apache Releases https://repository.apache.org/content/repositories/releases .
