### ISSUE TITLE
[MPMD-244] Maven PMD plugin fails but no reason is given for the failure

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-pmd-plugin#579]
**[Lyor Goldstein](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lgoldstein)** opened **[MPMD-244](https://issues.apache.org/jira/browse/MPMD-244?redirect=false)** and commented

After upgrading used PMD version from 5.6.1 to 5.8.1, Maven PMD plugin fails with no specific reason except `Failed to process...`. Furthermore, there is no PMD report or other file that indicates what is wrong.

P.S. The file that it complains about passes without a problem for version 5.6.1

```
$  mvn -X -Dpmd.verbose=true clean install
Maven home: /home/lyor/Software/apache-maven-3.5.0
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-2.b14.fc22.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.14-200.fc22.x86_64", arch: "amd64", family: "unix"
.....
......
[INFO] --- maven-pmd-plugin:3.8:pmd (pmd) @ cb4-common-util ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=1, ConflictMarker.markTime=0, ConflictMarker.nodeCount=280, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=70, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=2, ConflictResolver.conflictItemCount=152, DefaultDependencyCollector.collectTime=38, DefaultDependencyCollector.transformTime=3}
[DEBUG] org.apache.maven.plugins:maven-pmd-plugin:jar:3.8:
[DEBUG]    net.sourceforge.pmd:pmd-core:jar:5.8.1:runtime
[DEBUG]       com.beust:jcommander:jar:1.48:runtime
[DEBUG]       jaxen:jaxen:jar:1.1.6:runtime
[DEBUG]       net.java.dev.javacc:javacc:jar:5.0:runtime
[DEBUG]       net.sourceforge.saxon:saxon:jar:9.1.0.8:runtime
[DEBUG]       org.apache.commons:commons-lang3:jar:3.4:runtime
[DEBUG]       org.ow2.asm:asm:jar:5.0.4:runtime
[DEBUG]       com.google.code.gson:gson:jar:2.5:runtime
[DEBUG]       net.sourceforge.saxon:saxon:jar:dom:9.1.0.8:runtime
[DEBUG]    net.sourceforge.pmd:pmd-java:jar:5.8.1:runtime
[DEBUG]    net.sourceforge.pmd:pmd-javascript:jar:5.8.1:runtime
[DEBUG]       org.mozilla:rhino:jar:1.7.7:runtime
[DEBUG]    net.sourceforge.pmd:pmd-jsp:jar:5.8.1:runtime
[DEBUG]    org.apache.maven:maven-artifact:jar:2.2.1:compile
[DEBUG]    org.apache.maven:maven-model:jar:2.2.1:compile
[DEBUG]    org.apache.maven:maven-plugin-api:jar:2.2.1:compile
[DEBUG]    org.apache.maven:maven-project:jar:2.2.1:compile
[DEBUG]       org.apache.maven:maven-settings:jar:2.2.1:compile
[DEBUG]       org.apache.maven:maven-profile:jar:2.2.1:compile
[DEBUG]       org.apache.maven:maven-artifact-manager:jar:2.2.1:compile
[DEBUG]          org.apache.maven:maven-repository-metadata:jar:2.2.1:compile
[DEBUG]          backport-util-concurrent:backport-util-concurrent:jar:3.1:compile
[DEBUG]       org.apache.maven:maven-plugin-registry:jar:2.2.1:compile
[DEBUG]       org.codehaus.plexus:plexus-interpolation:jar:1.11:compile
[DEBUG]       org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile
[DEBUG]          junit:junit:jar:3.8.1:compile
[DEBUG]          classworlds:classworlds:jar:1.1-alpha-2:compile
[DEBUG]    org.apache.maven.doxia:doxia-sink-api:jar:1.4:compile
[DEBUG]       org.apache.maven.doxia:doxia-logging-api:jar:1.4:compile
[DEBUG]    org.apache.maven.doxia:doxia-decoration-model:jar:1.4:compile
[DEBUG]       org.codehaus.plexus:plexus-component-annotations:jar:1.6:compile
[DEBUG]    org.apache.maven.doxia:doxia-site-renderer:jar:1.4:compile
[DEBUG]       org.apache.maven.doxia:doxia-core:jar:1.4:compile
[DEBUG]          xerces:xercesImpl:jar:2.9.1:compile
[DEBUG]          commons-lang:commons-lang:jar:2.4:compile
[DEBUG]       org.apache.maven.doxia:doxia-module-xhtml:jar:1.4:compile
[DEBUG]       org.apache.maven.doxia:doxia-module-fml:jar:1.4:compile
[DEBUG]       org.codehaus.plexus:plexus-i18n:jar:1.0-beta-7:compile
[DEBUG]       org.codehaus.plexus:plexus-velocity:jar:1.1.7:compile
[DEBUG]       org.apache.velocity:velocity:jar:1.5:compile
[DEBUG]          oro:oro:jar:2.0.8:compile
[DEBUG]       org.apache.velocity:velocity-tools:jar:2.0:compile
[DEBUG]          commons-beanutils:commons-beanutils:jar:1.7.0:compile
[DEBUG]          commons-digester:commons-digester:jar:1.8:compile
[DEBUG]          commons-chain:commons-chain:jar:1.1:compile
[DEBUG]          sslext:sslext:jar:1.2-0:compile
[DEBUG]          org.apache.struts:struts-core:jar:1.3.8:compile
[DEBUG]             antlr:antlr:jar:2.7.2:compile
[DEBUG]          org.apache.struts:struts-taglib:jar:1.3.8:compile
[DEBUG]          org.apache.struts:struts-tiles:jar:1.3.8:compile
[DEBUG]       commons-collections:commons-collections:jar:3.2.1:compile
[DEBUG]    org.apache.maven.reporting:maven-reporting-api:jar:3.0:compile
[DEBUG]    org.apache.maven.reporting:maven-reporting-impl:jar:2.3:compile
[DEBUG]       org.apache.maven.shared:maven-shared-utils:jar:0.6:compile
[DEBUG]          com.google.code.findbugs:jsr305:jar:2.0.1:compile
[DEBUG]       commons-validator:commons-validator:jar:1.3.1:compile
[DEBUG]    org.codehaus.plexus:plexus-resources:jar:1.0.1:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:3.0.24:compile
[DEBUG]    org.apache.httpcomponents:httpclient:jar:4.3.5:compile
[DEBUG]       org.apache.httpcomponents:httpcore:jar:4.3.2:compile
[DEBUG]       commons-logging:commons-logging:jar:1.1.3:compile
[DEBUG]       commons-codec:commons-codec:jar:1.6:compile
[DEBUG]    commons-io:commons-io:jar:2.5:compile
[DEBUG] Created new class realm plugin>org.apache.maven.plugins:maven-pmd-plugin:3.8
[DEBUG] Importing foreign packages into class realm plugin>org.apache.maven.plugins:maven-pmd-plugin:3.8
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>org.apache.maven.plugins:maven-pmd-plugin:3.8
[DEBUG]   Included: org.apache.maven.plugins:maven-pmd-plugin:jar:3.8
[DEBUG]   Included: net.sourceforge.pmd:pmd-core:jar:5.8.1
[DEBUG]   Included: com.beust:jcommander:jar:1.48
[DEBUG]   Included: jaxen:jaxen:jar:1.1.6
[DEBUG]   Included: net.java.dev.javacc:javacc:jar:5.0
[DEBUG]   Included: net.sourceforge.saxon:saxon:jar:9.1.0.8
[DEBUG]   Included: org.apache.commons:commons-lang3:jar:3.4
[DEBUG]   Included: org.ow2.asm:asm:jar:5.0.4
[DEBUG]   Included: com.google.code.gson:gson:jar:2.5
[DEBUG]   Included: net.sourceforge.saxon:saxon:jar:dom:9.1.0.8
[DEBUG]   Included: net.sourceforge.pmd:pmd-java:jar:5.8.1
[DEBUG]   Included: net.sourceforge.pmd:pmd-javascript:jar:5.8.1
[DEBUG]   Included: org.mozilla:rhino:jar:1.7.7
[DEBUG]   Included: net.sourceforge.pmd:pmd-jsp:jar:5.8.1
[DEBUG]   Included: backport-util-concurrent:backport-util-concurrent:jar:3.1
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.11
[DEBUG]   Included: junit:junit:jar:3.8.1
[DEBUG]   Included: org.apache.maven.doxia:doxia-sink-api:jar:1.4
[DEBUG]   Included: org.apache.maven.doxia:doxia-logging-api:jar:1.4
[DEBUG]   Included: org.apache.maven.doxia:doxia-decoration-model:jar:1.4
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.6
[DEBUG]   Included: org.apache.maven.doxia:doxia-site-renderer:jar:1.4
[DEBUG]   Included: org.apache.maven.doxia:doxia-core:jar:1.4
[DEBUG]   Included: xerces:xercesImpl:jar:2.9.1
[DEBUG]   Included: commons-lang:commons-lang:jar:2.4
[DEBUG]   Included: org.apache.maven.doxia:doxia-module-xhtml:jar:1.4
[DEBUG]   Included: org.apache.maven.doxia:doxia-module-fml:jar:1.4
[DEBUG]   Included: org.codehaus.plexus:plexus-i18n:jar:1.0-beta-7
[DEBUG]   Included: org.codehaus.plexus:plexus-velocity:jar:1.1.7
[DEBUG]   Included: org.apache.velocity:velocity:jar:1.5
[DEBUG]   Included: oro:oro:jar:2.0.8
[DEBUG]   Included: org.apache.velocity:velocity-tools:jar:2.0
[DEBUG]   Included: commons-beanutils:commons-beanutils:jar:1.7.0
[DEBUG]   Included: commons-digester:commons-digester:jar:1.8
[DEBUG]   Included: commons-chain:commons-chain:jar:1.1
[DEBUG]   Included: sslext:sslext:jar:1.2-0
[DEBUG]   Included: org.apache.struts:struts-core:jar:1.3.8
[DEBUG]   Included: antlr:antlr:jar:2.7.2
[DEBUG]   Included: org.apache.struts:struts-taglib:jar:1.3.8
[DEBUG]   Included: org.apache.struts:struts-tiles:jar:1.3.8
[DEBUG]   Included: commons-collections:commons-collections:jar:3.2.1
[DEBUG]   Included: org.apache.maven.reporting:maven-reporting-api:jar:3.0
[DEBUG]   Included: org.apache.maven.reporting:maven-reporting-impl:jar:2.3
[DEBUG]   Included: org.apache.maven.shared:maven-shared-utils:jar:0.6
[DEBUG]   Included: com.google.code.findbugs:jsr305:jar:2.0.1
[DEBUG]   Included: commons-validator:commons-validator:jar:1.3.1
[DEBUG]   Included: org.codehaus.plexus:plexus-resources:jar:1.0.1
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.0.24
[DEBUG]   Included: org.apache.httpcomponents:httpclient:jar:4.3.5
[DEBUG]   Included: org.apache.httpcomponents:httpcore:jar:4.3.2
[DEBUG]   Included: commons-logging:commons-logging:jar:1.1.3
[DEBUG]   Included: commons-codec:commons-codec:jar:1.6
[DEBUG]   Included: commons-io:commons-io:jar:2.5
[DEBUG] Configuring mojo org.apache.maven.plugins:maven-pmd-plugin:3.8:pmd from plugin realm ClassRealm[plugin>org.apache.maven.plugins:maven-pmd-plugin:3.8, parent: sun.misc.Launcher$AppClassLoader@70dea4e]
[DEBUG] Setting property: classpath.resource.loader.class => 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader'.
[DEBUG] Setting property: site.resource.loader.class => 'org.codehaus.plexus.velocity.SiteResourceLoader'.
[DEBUG] Setting property: velocimacro.messages.on => 'false'.
[DEBUG] Setting property: resource.loader => 'classpath,site'.
[DEBUG] Setting property: runtime.log.invalid.references => 'false'.
[DEBUG] Setting property: resource.manager.logwhenfound => 'false'.
[DEBUG] Setting property: velocimacro.permissions.allow.inline.to.replace.global => 'true'.
[DEBUG] *******************************************************************
[DEBUG] Starting Apache Velocity v1.5 (compiled: 2007-02-22 08:52:29)
[DEBUG] RuntimeInstance initializing.
[DEBUG] Default Properties File: org/apache/velocity/runtime/defaults/velocity.properties
[DEBUG] LogSystem has been deprecated. Please use a LogChute implementation.
[DEBUG] Default ResourceManager initializing. (class org.apache.velocity.runtime.resource.ResourceManagerImpl)
[DEBUG] ResourceLoader instantiated: org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader
[DEBUG] ResourceLoader instantiated: org.codehaus.plexus.velocity.SiteResourceLoader
[DEBUG] ResourceCache: initialized (class org.apache.velocity.runtime.resource.ResourceCacheImpl)
[DEBUG] Default ResourceManager initialization complete.
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Literal
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Macro
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Parse
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Include
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Foreach
[DEBUG] Created '20' parsers.
[DEBUG] Velocimacro : initialization starting.
[DEBUG] Velocimacro : allowInline = true : VMs can be defined inline in templates
[DEBUG] Velocimacro : allowInlineToOverride = true : VMs defined inline may replace previous VM definitions
[DEBUG] Velocimacro : allowInlineLocal = false : VMs defined inline will be global in scope if allowed.
[DEBUG] Velocimacro : autoload off : VM system will not automatically reload global library macros
[DEBUG] Velocimacro : Velocimacro : initialization complete.
[DEBUG] RuntimeInstance successfully initialized.
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-pmd-plugin:3.8:pmd' with basic configurator -->
[DEBUG]   (f) aggregate = false
[DEBUG]   (f) analysisCache = false
[DEBUG]   (f) analysisCacheLocation = /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/target/pmd/pmd.cache
[DEBUG]   (f) benchmark = false
[DEBUG]   (f) benchmarkOutputFilename = /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/target/pmd-benchmark.txt
[DEBUG]   (f) compileSourceRoots = [/home/lyor/workspace/C-B4-Server/commons/cb4-common-util/src/main/java, /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/target/generated-sources/annotations]
[DEBUG]   (f) excludeRoots = [/home/lyor/workspace/C-B4-Server/commons/cb4-common-util/target/generated-sources/java]
[DEBUG]   (f) format = xml
[DEBUG]   (f) includeTests = true
[DEBUG]   (f) includeXmlInSite = false
[DEBUG]   (f) inputEncoding = UTF-8
[DEBUG]   (f) language = java
[DEBUG]   (f) linkXRef = true
[DEBUG]   (f) minimumPriority = 5
[DEBUG]   (f) outputDirectory = /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/target/site
[DEBUG]   (f) outputEncoding = UTF-8
[DEBUG]   (f) project = MavenProject: com.cb4.commons:cb4-common-util:3.2.19-SNAPSHOT @ /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/pom.xml
[DEBUG]   (f) reactorProjects = [MavenProject: com.cb4.commons:cb4-common-util:3.2.19-SNAPSHOT @ /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/pom.xml]
[DEBUG]   (s) rulesets = [file:/home/lyor/workspace/C-B4-Server/pmd-ruleset-cb4.xml]
[DEBUG]   (f) skip = false
[DEBUG]   (f) skipEmptyReport = true
[DEBUG]   (f) skipPmdError = false
[DEBUG]   (f) sourceEncoding = UTF-8
[DEBUG]   (f) targetDirectory = /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/target
[DEBUG]   (f) targetJdk = 1.8
[DEBUG]   (f) testSourceRoots = [/home/lyor/workspace/C-B4-Server/commons/cb4-common-util/src/test/java, /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/target/generated-test-sources/test-annotations]
[DEBUG]   (f) typeResolution = true
[DEBUG]   (f) xrefLocation = /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/target/site/xref
[DEBUG]   (f) xrefTestLocation = /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/target/site/xref-test
[DEBUG] -- end configuration --
[DEBUG] Using language LanguageModule:Java(JavaLanguageModule)+version:1.8
[DEBUG] Using aux classpath: [/home/lyor/workspace/C-B4-Server/commons/cb4-common-util/target/test-classes, /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/target/classes, /home/lyor/.m2/repository/org/apache/commons/commons-lang3/3.6/commons-lang3-3.6.jar, /home/lyor/.m2/repository/org/apache/commons/commons-text/1.1/commons-text-1.1.jar, /home/lyor/.m2/repository/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.jar, /home/lyor/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar, /home/lyor/.m2/repository/commons-cli/commons-cli/1.4/commons-cli-1.4.jar, /home/lyor/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar, /home/lyor/.m2/repository/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar, /home/lyor/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar, /home/lyor/.m2/repository/com/opencsv/opencsv/3.10/opencsv-3.10.jar, /home/lyor/.m2/repository/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar, /home/lyor/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar, /home/lyor/.m2/repository/com/univocity/univocity-parsers/2.5.6/univocity-parsers-2.5.6.jar, /home/lyor/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.9.1/jackson-dataformat-csv-2.9.1.jar, /home/lyor/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.1/jackson-annotations-2.9.1.jar, /home/lyor/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.1/jackson-core-2.9.1.jar, /home/lyor/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.1/jackson-databind-2.9.1.jar, /home/lyor/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar, /home/lyor/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar, /home/lyor/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar, /home/lyor/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar, /home/lyor/.m2/repository/junit/junit/4.12/junit-4.12.jar, /home/lyor/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar, /home/lyor/.m2/repository/org/mockito/mockito-all/1.10.19/mockito-all-1.10.19.jar]
[DEBUG] Preparing ruleset: file:/home/lyor/workspace/C-B4-Server/pmd-ruleset-cb4.xml
[DEBUG] Before: file:/home/lyor/workspace/C-B4-Server/pmd-ruleset-cb4.xml After: pmd-ruleset-cb4.xml
[DEBUG] URLResourceLoader: Found 'file:/home/lyor/workspace/C-B4-Server/pmd-ruleset-cb4.xml' at ''
[DEBUG] The resource 'file:/home/lyor/workspace/C-B4-Server/pmd-ruleset-cb4.xml' was found as file:/home/lyor/workspace/C-B4-Server/pmd-ruleset-cb4.xml.
[DEBUG] Exclusions: **/*~,**/#*#,**/.#*,**/%*%,**/._*,**/CVS,**/CVS/**,**/.cvsignore,**/RCS,**/RCS/**,**/SCCS,**/SCCS/**,**/vssver.scc,**/project.pj,**/.svn,**/.svn/**,**/.arch-ids,**/.arch-ids/**,**/.bzr,**/.bzr/**,**/.MySCMServerInfo,**/.DS_Store,**/.metadata,**/.metadata/**,**/.hg,**/.hgignore,**/.hg/**,**/.git,**/.gitignore,**/.gitattributes,**/.git/**,**/BitKeeper,**/BitKeeper/**,**/ChangeSet,**/ChangeSet/**,**/_darcs,**/_darcs/**,**/.darcsrepo,**/.darcsrepo/**,**/-darcs-backup*,**/.darcs-temp-mail
[DEBUG] Inclusions: **/*.java
[DEBUG] Searching for files in directory /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/src/main/java
[DEBUG] Searching for files in directory /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/target/generated-sources/annotations
[DEBUG] Searching for files in directory /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/src/test/java
[DEBUG] Searching for files in directory /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/target/generated-test-sources/test-annotations
[DEBUG] Executing PMD...
[DEBUG] PMD finished. Found 0 violations.
[ERROR] PMD processing errors:
[ERROR] /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/src/test/java/com/cb4/common/utils/MapUtilsTest.java: Error while processing /home/lyor/workspace/C-B4-Server/commons/cb4-common-util/src/test/java/com/cb4/common/utils/MapUtilsTest.java
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.248 s
[INFO] Finished at: 2017-09-24T12:30:52+03:00
[INFO] Final Memory: 64M/1305M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.8:pmd (pmd) on project cb4-common-util: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.8:pmd failed: org.apache.maven.reporting.MavenReportException: Found 1 PMD processing errors -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.8:pmd (pmd) on project cb4-common-util: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.8:pmd failed: org.apache.maven.reporting.MavenReportException: Found 1 PMD processing errors
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:353)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:198)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.8:pmd failed: org.apache.maven.reporting.MavenReportException: Found 1 PMD processing errors
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 24 more
Caused by: java.lang.RuntimeException: org.apache.maven.reporting.MavenReportException: Found 1 PMD processing errors
        at org.apache.maven.plugin.pmd.PmdReport.canGenerateReport(PmdReport.java:298)
        at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:119)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 25 more
Caused by: org.apache.maven.reporting.MavenReportException: Found 1 PMD processing errors
        at org.apache.maven.plugin.pmd.PmdReport.executePmd(PmdReport.java:420)
        at org.apache.maven.plugin.pmd.PmdReport.executePmdWithClassloader(PmdReport.java:311)
        at org.apache.maven.plugin.pmd.PmdReport.canGenerateReport(PmdReport.java:285)
        ... 27 more
```

---

**Affects:** 3.8

**Issue Links:**
- [MPMD-258](https://issues.apache.org/jira/browse/MPMD-258) PMD output multiplies with every module in multi module projects

- [MPMD-292](https://issues.apache.org/jira/browse/MPMD-292) PMD Log is not always integrated into maven log

- [MPMD-246](https://issues.apache.org/jira/browse/MPMD-246) Output details of processing errors

**Comment by jira-importer** [comment]
**[Andreas Dangel](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=adangel)** commented

[Lyor Goldstein](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lgoldstein) This looks like a PMD problem. Could you please file an issue at https://github.com/pmd/pmd/issues and attach the problematic file (`/home/lyor/workspace/C-B4-Server/commons/cb4-common-util/src/test/java/com/cb4/common/utils/MapUtilsTest.java`)? Thanks!

**Comment by jira-importer** [comment]
**[Lyor Goldstein](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lgoldstein)** commented

Done - opened [Issue #650](https://github.com/pmd/pmd/issues/650) if you wish to track it

**Comment by jira-importer** [comment]
**[Andreas Dangel](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=adangel)** commented

With MPMD-246, we add the details of the processing errors to the report.

However, it would still be interesting to see the logs of PMD itself, when run through m-pmd-p. This is indeed already possible.

1. Create a file `logging.properties` with the following content:

```
handlers=java.util.logging.ConsoleHandler

java.util.logging.ConsoleHandler.level=ALL
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
net.sourceforge.pmd.level = ALL
```

2. Run maven with additional options: `MAVEN_OPTS="-Djava.util.logging.config.file=logging.properties" mvn pmd:pmd`

When this bug is fixed, the logs of PMD are integrated into the output of maven. Thus, running maven with the debug flag (-X) enables the debug logging of PMD, too.

**Comment by jira-importer** [comment]
**[Andreas Dangel](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=adangel)** commented

With 3.9.0 a new parameter has been added for both PMD and CPD, which is enabled by default:

Name: **showPmdLog** (property = "pmd.showPmdLog")

When enabled, the PMD log output is redirected to maven, so that
it is visible in the console together with all the other log output.
Also, if maven is started with the debug flag (`-X` or `--debug`)
the PMD logger is also configured for debug.
